(cl:in-package custom_msg-msg)
(cl:export '(X1-VAL
          X1
          Y1-VAL
          Y1
          A1-VAL
          A1
          C1-VAL
          C1
          X2-VAL
          X2
          Y2-VAL
          Y2
          A2-VAL
          A2
          C2-VAL
          C2
          X3-VAL
          X3
          Y3-VAL
          Y3
          A3-VAL
          A3
          C3-VAL
          C3
          X4-VAL
          X4
          Y4-VAL
          Y4
          A4-VAL
          A4
          C4-VAL
          C4
))