(cl:defpackage opencv_services-srv
  (:use )
  (:export
   "BOX_AND_TARGET_POSITION"
   "<BOX_AND_TARGET_POSITION-REQUEST>"
   "BOX_AND_TARGET_POSITION-REQUEST"
   "<BOX_AND_TARGET_POSITION-RESPONSE>"
   "BOX_AND_TARGET_POSITION-RESPONSE"
  ))

