// Generated by gencpp from file opencv_services/box_and_target_position.msg
// DO NOT EDIT!


#ifndef OPENCV_SERVICES_MESSAGE_BOX_AND_TARGET_POSITION_H
#define OPENCV_SERVICES_MESSAGE_BOX_AND_TARGET_POSITION_H

#include <ros/service_traits.h>


#include <opencv_services/box_and_target_positionRequest.h>
#include <opencv_services/box_and_target_positionResponse.h>


namespace opencv_services
{

struct box_and_target_position
{

typedef box_and_target_positionRequest Request;
typedef box_and_target_positionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct box_and_target_position
} // namespace opencv_services


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::opencv_services::box_and_target_position > {
  static const char* value()
  {
    return "305b8cdaf6eafb69d6dc3217db2db095";
  }

  static const char* value(const ::opencv_services::box_and_target_position&) { return value(); }
};

template<>
struct DataType< ::opencv_services::box_and_target_position > {
  static const char* value()
  {
    return "opencv_services/box_and_target_position";
  }

  static const char* value(const ::opencv_services::box_and_target_position&) { return value(); }
};


// service_traits::MD5Sum< ::opencv_services::box_and_target_positionRequest> should match
// service_traits::MD5Sum< ::opencv_services::box_and_target_position >
template<>
struct MD5Sum< ::opencv_services::box_and_target_positionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::opencv_services::box_and_target_position >::value();
  }
  static const char* value(const ::opencv_services::box_and_target_positionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::opencv_services::box_and_target_positionRequest> should match
// service_traits::DataType< ::opencv_services::box_and_target_position >
template<>
struct DataType< ::opencv_services::box_and_target_positionRequest>
{
  static const char* value()
  {
    return DataType< ::opencv_services::box_and_target_position >::value();
  }
  static const char* value(const ::opencv_services::box_and_target_positionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::opencv_services::box_and_target_positionResponse> should match
// service_traits::MD5Sum< ::opencv_services::box_and_target_position >
template<>
struct MD5Sum< ::opencv_services::box_and_target_positionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::opencv_services::box_and_target_position >::value();
  }
  static const char* value(const ::opencv_services::box_and_target_positionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::opencv_services::box_and_target_positionResponse> should match
// service_traits::DataType< ::opencv_services::box_and_target_position >
template<>
struct DataType< ::opencv_services::box_and_target_positionResponse>
{
  static const char* value()
  {
    return DataType< ::opencv_services::box_and_target_position >::value();
  }
  static const char* value(const ::opencv_services::box_and_target_positionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPENCV_SERVICES_MESSAGE_BOX_AND_TARGET_POSITION_H
